language: node_js
node_js:
  - "4.2.6"
script:
  - grunt
before_script:
  - npm install grunt-cli -g
after_success:
  - npm run coveralls
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
