sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^3.0.0
install:
  - npm install
script:
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script: npm run semantic-release
  on:
    branch: next
