language: node_js
notifications:
  email: true
node_js:
  - '6'
script:
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+.*/
after_success:
  if ([ "$TRAVIS_BRANCH" == "next" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    eval 'npm run semantic-release';
  fi
